name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to target repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "jagjeetsinghsandhu22129@gmail.com"
          git config --global user.name "jagjeetsinghsandhu22129"
          git remote add target_repo https://$GH_PAT@github.com/jagjeetsinghsandhu22129/PROG8840_Group_6.git
          git push target_repo main
