name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write # Grant write permissions for repository contents

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' # or '7.0.x' if you choose to downgrade

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Push code to PROG8840_Group_6
      run: |
        git config --global user.email "jagjeetsinghsandhu22129@gmail.com"
        git config --global user.name "jagjeetsinghsandhu22129"
        git remote add target_repo https://github.com/jagjeetsinghsandhu22129/PROG8840_Group_6.git
        git push target_repo main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure to use the default GITHUB_TOKEN
